name: $(date:yy)$(DayOfYear)$(rev:.r)

trigger:
  - master
  - releases/shipped

variables:
  majorAndMinorVersion: '0.5'
  revision: '$(Build.BuildNumber)'

jobs:
  - job: Build
    strategy:
      maxParallel: 2
      matrix:
        debug:
          configuration: Debug
        release:
          configuration: Release
    pool:
      vmImage: vs2017-win2016
    steps:
    - template: templates/build-and-unit-test.yml

  - job: FunctionalTests
    timeoutInMinutes: 240
    variables:
      configuration: Release
    pool:
      name: FunctionalTests
    dependsOn: Build
    condition: succeeded()
    steps:
    - checkout: none # We'll get the build drop from Build job
    - template: templates/functional-test.yml
