name: $(date:yy)$(DayOfYear)$(rev:.r)

trigger: none

variables:
  majorAndMinorVersion: '0.4'
  revision: '$(Build.BuildNumber)'
  platform: 'x64'
  configuration: release

jobs:
  - job: Build
    pool:
      vmImage: vs2017-win2016
    steps:
    - template: templates/build-and-unit-test.yml
